# Generated by Django 5.0.4 on 2024-04-23 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(editable=False, max_length=256)),
                ('abbreviation', models.CharField(editable=False, max_length=32, unique=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'coin'), (1, 'token')], db_index=True, default=0)),
                ('exchange', models.PositiveSmallIntegerField(choices=[(0, 'aban'), (1, 'kucoin'), (2, 'coinex')], db_index=True, default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('amount', models.FloatField()),
                ('cost', models.FloatField()),
                ('status', models.SmallIntegerField(choices=[(0, 'reserved'), (1, 'queued'), (2, 'in_process'), (3, 'finished'), (4, 'failed'), (5, 'scheduled')], db_index=True, default=0)),
                ('asset', models.ManyToManyField(db_index=True, related_name='orders', to='portfolio_management.asset')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('amount', models.FloatField(default=0)),
                ('asset', models.ManyToManyField(related_name='portfolios', to='portfolio_management.asset')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
